### ISSUE TITLE
Make sex variable values sentence case

### ISSUE THREAD

**Issue by davidhodge931** [allisonhorst/palmerpenguins#79]

**Comment by davidhodge931** [comment]
While perhaps pedantic, I think it'd be great if this is more tidy

**Comment by allisonhorst** [comment]
Hi @davidhodge931, thanks for the feedback. Since this version of the data has been on CRAN for almost a year, this could be a change that would break existing code for some, and since this is a lightweight data package, we’d like to err on the side of caution making changes to the data itself. We hope this gives instructors a good use case for teaching functions like `stringr::str_to_sentence` :slightly_smiling_face: [https://stringr.tidyverse.org/reference/case.html](https://stringr.tidyverse.org/reference/case.html)

**Comment by davidhodge931** [comment]
Thanks @allisonhorst 

Appreciate the dataset :) 

I'm using it in examples for the visualisation package I'm developing
https://statisticsnz.github.io/simplevis/articles/simplevis.html
