### ISSUE TITLE
Vignettes not accessible from package

### ISSUE THREAD

**Issue by statisfactions** [allisonhorst/palmerpenguins#83]
``` r
library(palmerpenguins)
sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Mojave 10.14.6
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] palmerpenguins_0.1.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.5  magrittr_1.5    tools_4.0.5     htmltools_0.5.0
#>  [5] yaml_2.2.1      stringi_1.4.6   rmarkdown_2.6   highr_0.8      
#>  [9] knitr_1.29      stringr_1.4.0   xfun_0.15       digest_0.6.25  
#> [13] rlang_0.4.7     evaluate_0.14
vignette(package = "palmerpenguins")
#> no vignettes found
```

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

[This discussion](https://stackoverflow.com/questions/33614660/knitr-rmd-vignettes-do-not-appear-with-vignette) may be relevant.

**Comment by allisonhorst** [comment]
Thanks @statisfactions , we appreciate you reaching out. This was intentional on our end to minimize package dependencies (expecting that the [package website](https://allisonhorst.github.io/palmerpenguins/) will be the primary place that users access vignettes). The `vignettes/` folder is currently in the `.Rbuildignore` file so that it does not end up on CRAN and in the package, and stays just for pkgdown website.

**Comment by statisfactions** [comment]
Thanks, that makes sense!

Maybe you could remove the references to `vignette("examples")` and `vignette("art")`, in the README, since the vignettes are not accessible in that way?
